### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by milovanderlinden** [geopipes/osmium-stream#2]
When I run

```
npm install osmium-stream
```

I get the following error

```
Error: /home/user/project/node_modules/osmium-stream/node_modules/osmium/lib/binding/osmium.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3

node-pre-gyp ERR! Testing local pre-built binary failed, attempting to re-download 
[osmium] Success: "/home/user/project/node_modules/osmium-stream/node_modules/osmium/lib/binding/osmium.node" is reinstalled via remote
osmium-stream@1.0.1 node_modules/osmium-stream
└── osmium@0.3.0
```

Can it be that the module tries to install the osmosium files and during the process finds that I am on a 64 bit architecture whilst it downloaded 32 bit osmosium?

I am going to dig into this issue a little deeper.

**Comment by milovanderlinden** [comment]
This is an issue I have with osmium, not with osmium-stream. Closing.

**Comment by missinglink** [comment]
yep, I have always had that issue, it seems to work for me anyway.
it's still annoying as it makes the unit tests fail.

did you report it to them?
